### ISSUE TITLE
When compiling C code, for some libraries `-lm` needs to added manually for static builds

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/stb#4]
Saw this item in the README (with the suggestion that this could be a `build2` bug). This should work provided you add `-lm` in `c.libs`, not only `export.c.libs`. I.e., instead of just:

```
export.c.libs = -lm
```

You need:

```
c.libs = -lm
export.c.libs = -lm
```

Even for header-only libraries.

**Comment by lyrahgames** [comment]
Thank you so much for the remark and, indeed, the solution. I would have asked about it myself in a few days and I did not want to put the fault onto the build2 site but needed a reminder and a note in the `README.md`.

> Even for header-only libraries.

Still, I do not understand why we need to use `c.libs = -lm`. Up to now, I thought it would only affect the local library compilation. As I tried to package a header-only library, I considered there would be no such step.

In the following, you can find the new CI builds for the respective packages. I have already published them and will close the issue with this commit.

- [`stb_easy_font` CI](https://ci.cppget.org/@b99e4952-7197-4967-80e9-8b8c51d7801c)
- [`stb_hexwave` CI](https://ci.cppget.org/@ffd4e425-0ac7-4a97-ac4d-3e305e75e947)
- [`stb_image` CI](https://ci.cppget.org/@6b3426fa-0cd1-438a-8141-46fc10c1f514)
- [`stb_image_resize` CI](https://ci.cppget.org/@89132daf-3585-4b98-a2d2-e173d7d480f7)
- [`stb_vorbis` CI](https://ci.cppget.org/@dd94a47b-3f47-49cf-809d-5cbf008902c1)

**Comment by boris-kolpackov** [comment]
> Still, I do not understand why we need to use `c.libs = -lm`. 

Ok, I've finally found time to write something up on this:

https://github.com/build2/HOWTO/blob/master/entries/make-header-only-library.md

For background, see:

https://build2.org/stage/build2/doc/build2-build-system-manual.xhtml#intro-lib
